#!/bin/sh

set -e

if [ "$1" = "remove" ]; then
    rm -f /var/lib/cmprovision/.env
    rm -rf /var/lib/cmprovision/storage /var/lib/cmprovision/database
fi

# Automatically added by dh_systemd_start/12.10ubuntu1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/12.10ubuntu1
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'cmprovision-dnsmasq.service' 'cmprovision-rpiboot.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'cmprovision-dnsmasq.service' 'cmprovision-rpiboot.service' >/dev/null || true
		deb-systemd-helper unmask 'cmprovision-dnsmasq.service' 'cmprovision-rpiboot.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
